[versions]
agp = "8.6.1"
flexbox = "3.0.0"
flexboxVersion = "3.0.0"
glide = "4.15.1"
googleMaterialVersion = "1.6.1"
javafaker = "1.0.2"
kotlin = "1.9.22"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
androidxAppcompat = "1.6.1"
appcompat = "1.7.0"
kotlinReflect = "1.9.22"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
materialVersion = "1.9.0"
navigationFragmentKtx = "2.5.0"
retrofitVersion = "2.9.0"
cronetEmbedded = "119.6045.31"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
android-flexbox = { module = "com.google.android:flexbox", version.ref = "flexboxVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-material-v161 = { module = "com.google.android.material:material", version.ref = "googleMaterialVersion" }
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "javafaker" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
cronet-embedded = { group = "org.chromium.net", name = "cronet-embedded", version.ref = "cronetEmbedded" }